#!/usr/bin/env python3
"""Fine-tune the model by retrofitting the ACTUAL group-stage results.

We hold the pre-tournament Elo ratings fixed and search for the principle values
(scoring level, goal sensitivity, home advantage) that best reproduce what really
happened in the 72 group games — each team's goals for, goals against, and points.

Fit metric: sum of squared error between the model's EXPECTED (gf, ga, pts) for
every team across its three actual fixtures and the OBSERVED values.

  python3 calibrate.py            # report best-fit params + before/after
  python3 calibrate.py --write    # also write principles_calibrated.py
"""
import argparse
import copy
import csv
import itertools
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "src"))
from engine import match_probs                       # noqa: E402
from tournament import load_teams, GROUPS            # noqa: E402
from principles import PRINCIPLES as BASE            # noqa: E402

ROOT = Path(__file__).parent
TEAMS = ROOT / "data" / "teams.csv"
RESULTS = ROOT / "data" / "group_results.csv"

# search grid for the three knobs the group data actually informs
GRID = {
    "avg_goals_per_team": [round(1.15 + 0.05 * i, 2) for i in range(13)],  # 1.15..1.75
    "goal_elo_beta":      [round(0.25 + 0.05 * i, 2) for i in range(17)],  # 0.25..1.05
    "home_advantage_elo": list(range(0, 221, 20)),                        # 0..220
}
W_PTS = 1.0  # weight on the points term vs the two goals terms


def load_results():
    obs = {}
    with open(RESULTS, newline="") as f:
        for r in csv.DictReader(f):
            obs[r["team"]] = (float(r["gf"]), float(r["ga"]), float(r["pts"]))
    return obs


def fit(teams, obs, P):
    """Sum-of-squared-error of expected vs observed (gf, ga, pts) per team."""
    by_group = {}
    for t in teams.values():
        by_group.setdefault(t.group, []).append(t)
    err = 0.0
    for g in GROUPS:
        gt = by_group[g]
        for a in gt:
            egf = ega = epts = 0.0
            for b in gt:
                if a is b:
                    continue
                m = match_probs(a, b, P, gmax=9)
                egf += m["xg_a"]; ega += m["xg_b"]
                epts += 3 * m["win"] + m["draw"]
            gf, ga, pts = obs[a.name]
            err += (egf - gf) ** 2 + (ega - ga) ** 2 + W_PTS * (epts - pts) ** 2
    return err


def goals_per_match(teams, P):
    by_group = {}
    for t in teams.values():
        by_group.setdefault(t.group, []).append(t)
    tot = n = 0.0
    for gt in by_group.values():
        for a, b in itertools.combinations(gt, 2):
            m = match_probs(a, b, P, gmax=9)
            tot += m["xg_a"] + m["xg_b"]; n += 1
    return tot / n


def search(teams, obs):
    best, best_err = None, float("inf")
    for mu in GRID["avg_goals_per_team"]:
        for beta in GRID["goal_elo_beta"]:
            for ha in GRID["home_advantage_elo"]:
                P = copy.deepcopy(BASE)
                P.update(avg_goals_per_team=mu, goal_elo_beta=beta, home_advantage_elo=ha)
                e = fit(teams, obs, P)
                if e < best_err:
                    best_err, best = e, P
    return best, best_err


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="write principles_calibrated.py")
    args = ap.parse_args()
    teams = load_teams(TEAMS)
    obs = load_results()

    base_err = fit(teams, obs, BASE)
    best, best_err = search(teams, obs)

    keys = ["avg_goals_per_team", "goal_elo_beta", "home_advantage_elo"]
    print("Calibrating to 72 actual group matches (215 goals, 2.99/match)\n")
    print(f"{'knob':>22}   default    fitted")
    for k in keys:
        print(f"{k:>22}   {str(BASE[k]):>7}   {str(best[k]):>7}")
    print(f"\n{'fit (SSE, lower=better)':>30}")
    print(f"{'default params':>30}: {base_err:8.1f}   ({goals_per_match(teams, BASE):.2f} goals/match)")
    print(f"{'calibrated params':>30}: {best_err:8.1f}   ({goals_per_match(teams, best):.2f} goals/match)")
    print(f"{'improvement':>30}: {100*(1-best_err/base_err):7.1f}%   (actual: 2.99 goals/match)")

    if args.write:
        out = ROOT / "principles_calibrated.py"
        body = ",\n".join(f'    "{k}": {best[k]!r}' for k in best)
        out.write_text(
            '"""Auto-generated by calibrate.py — params fitted to actual group results."""\n'
            f"PRINCIPLES = {{\n{body},\n}}\n"
        )
        print(f"\nwrote {out.name}  ->  python3 predict.py --calibrated --actual")


if __name__ == "__main__":
    main()
