"""Auto-generated by calibrate.py — params fitted to actual group results."""
PRINCIPLES = {
    "elo_scale": 400.0,
    "avg_goals_per_team": 1.3,
    "goal_elo_beta": 0.8,
    "home_advantage_elo": 120,
    "concacaf_region_elo": 15.0,
    "form_weight": 1.0,
    "penalty_skill": 0.3,
    "n_sims": 20000,
    "random_seed": 42,
}
